### ISSUE TITLE
Installing this plugin alongside gitrocket breaks gitrocket

### ISSUE THREAD

**Issue by welnanick** [lukaszromerowicz/space-pull#1]
When I installed this plugin alongside gitrocket, gitrocket stopped functioning. When I removed this plugin, gitrocket started working again.

**Comment by lukaszromerowicz** [comment]
Thank you for raising an issue!
I will have a look into it and try to come up with a fix soon.

**Comment by lukaszromerowicz** [comment]
I have just pushed the fix that should resolve the issue. Try updating to the latest `1.0.12` version.
Thanks!

**Comment by welnanick** [comment]
gitrocket works now, but this plugin is still having trouble. The animation plays for a spit-second then disappears.

I'm using Hyper 1.4.8 on Windows10 if that helps at all.

**Comment by lukaszromerowicz** [comment]
Unfortunately I can't reproduce the issue using the same version of Hyper on Windows 10.
Are you using any plugins other than gitrocket alongside?

**Comment by welnanick** [comment]
The plugins I'm running are:
hyper-solarized-dark
hyperline
gitrocket
space-pull

The shell I'm using is cmd, not powershell, and I'm using git for windows version 2.16.2

**Comment by lukaszromerowicz** [comment]
Just pushed the fix for the issue. Please try updating to `1.0.13` version.
Thanks!

**Comment by welnanick** [comment]
Works now! gitrocket and space-pull are working perfectly together now!

Also, just so you know, space-pull triggers on `git fetch` when there are updates on the remote repository as well. I don't know if this is intended or not, but figured I'd bring it up.

**Comment by lukaszromerowicz** [comment]
Great, thank you! Closing this issue as it is now resolved.
